using UnityEngine;

/// <summary>
/// Represents one socket point in a LEGO grid.
/// 
/// Sockets are generated by LegoBlockSocketSpawner and used by
/// LegoBlockGhostManager to calculate valid snap positions.
/// </summary>
public class LegoSocket : MonoBehaviour
{
    // -------------------------------------------------------------------------
    // Grid Data
    // -------------------------------------------------------------------------

    [HideInInspector] public bool isInnerSocket = true;
    [HideInInspector] public int gridX;
    [HideInInspector] public int gridZ;
    [HideInInspector] public LegoBlockSocketSpawner parentGrid;

    // -------------------------------------------------------------------------
    // Occupation State
    // -------------------------------------------------------------------------

    [Tooltip("True if this socket is currently occupied by a snapped block.")]
    public bool isOccupied;

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /// <summary>
    /// Returns the base rotation used when snapping a block to this socket.
    /// 
    /// If this socket belongs to another LEGO block, the parent block rotation is used.
    /// Otherwise, the socket's own world rotation is used.
    /// </summary>
    public Quaternion GetBaseRotation()
    {
        LegoBlock parentBlock = GetComponentInParent<LegoBlock>();

        if (parentBlock != null)
            return parentBlock.transform.rotation;

        return transform.rotation;
    }

    /// <summary>
    /// Returns a simple non-rotated snap position for this socket.
    /// 
    /// Most current snapping logic uses LegoBlockSocketSpawner directly,
    /// but this method is kept as a convenient fallback.
    /// </summary>
    public Vector3 GetSnapWorldPosition(LegoBlock block)
    {
        if (block == null)
            return transform.position;

        if (parentGrid != null)
        {
            System.Collections.Generic.List<Vector2Int> footprint = block.GetStudFootprint();
            System.Collections.Generic.List<Vector2Int> absoluteCells = new System.Collections.Generic.List<Vector2Int>(footprint.Count);

            for (int i = 0; i < footprint.Count; i++)
            {
                Vector2Int cell = footprint[i];
                absoluteCells.Add(new Vector2Int(gridX + cell.x, gridZ + cell.y));
            }

            return parentGrid.GetFootprintCenterWorldPosition(absoluteCells, block.GetWorldHeight());
        }

        return transform.TransformPoint(new Vector3(0f, block.GetWorldHeight(), 0f));
    }
}